### ISSUE TITLE
Common Array Elements 

### ISSUE THREAD

**Issue by rayvafa** [tomdaniels/javascript-challenges#5]
Write a javascript function that accepts two array as parameter, and return an array that contains common elements of the input arrays.
so I will call your function like this:

```
var array1 = [1, 20, 10, 100, 2];
var array2 = [500, 2, 20, 200];
var resultArray = commonArrayElements(array1, array2);
console.log(resultArray);
```

and the result should be: `[2, 20]`

**Comment by tomdaniels** [comment]
@rayvafa 
https://github.com/tomdaniels/javascript-challenges/pull/10
