### ISSUE TITLE
Difference between two arrays

### ISSUE THREAD

**Issue by rayvafa** [tomdaniels/javascript-challenges#6]
Write a javascript function that accepts two array as parameter, and return an array that contains elements that hasn't been in both arrays and sort the result using the previous function you wrote as part of #1 .
so I will call your function like this:

```
var array1 = [1, 20, 10, 100, 2];
var array2 = [500, 2, 20, 200];
var resultArray = commonArrayElements(array1, array2);
console.log(resultArray);
```

and the result should be: `[1, 10, 100, 200, 500]`

**Comment by tomdaniels** [comment]
https://github.com/tomdaniels/javascript-challenges/pull/11

**Comment by tomdaniels** [comment]
https://github.com/tomdaniels/javascript-challenges/pull/13
