### ISSUE TITLE
Reverse an array

### ISSUE THREAD

**Issue by rayvafa** [tomdaniels/javascript-challenges#7]
Write a javascript function that accepts one array as parameter, and return an array that is in reverse order.
so I will call your function like this:

```
var myArray = [1, 20, 10, 100, 2];
var resultArray = commonArrayElements(myArray);
console.log(resultArray);
```

and the result should be: `[2, 100, 10, 20, 1]`

**Comment by tomdaniels** [comment]
@rayvafa have pushed new branch `reverse-challenge`. 

Uses a reverse loop to order the Array regardless of value.

**Comment by tomdaniels** [comment]
@rayvafa this has been completed: 
https://github.com/tomdaniels/javascript-challenges/pull/9/commits/d394383df32eba9bd65c39a861a62c30a6526d32

**Comment by rayvafa** [comment]
nice 🎉
