### ISSUE TITLE
Title case a string

### ISSUE THREAD

**Issue by rayvafa** [tomdaniels/javascript-challenges#8]
Write a javascript function that accepts a string and title case it(I mean having first character of every word to be uppercase). 
so I will call your function like this:

```
var title = "my very loNg anD bEaUtIfUl tItlE!";
var resultTitle = titleCase(title);
console.log(resultTitle);
```

and the result should be: `My Very Long And Beautiful Title!`

**Comment by tomdaniels** [comment]
#12
